
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 3
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

    #define yy_create_buffer yy_create_buffer

    #define yy_delete_buffer yy_delete_buffer

    #define yy_scan_buffer yy_scan_buffer

    #define yy_scan_string yy_scan_string

    #define yy_scan_bytes yy_scan_bytes

    #define yy_init_buffer yy_init_buffer

    #define yy_flush_buffer yy_flush_buffer

    #define yy_load_buffer_state yy_load_buffer_state

    #define yy_switch_to_buffer yy_switch_to_buffer

    #define yypush_buffer_state yypush_buffer_state

    #define yypop_buffer_state yypop_buffer_state

    #define yyensure_buffer_stack yyensure_buffer_stack

    #define yylex yylex

    #define yyrestart yyrestart

    #define yylex_init yylex_init

    #define yylex_init_extra yylex_init_extra

    #define yylex_destroy yylex_destroy

    #define yyget_debug yyget_debug

    #define yyset_debug yyset_debug

    #define yyget_extra yyget_extra

    #define yyset_extra yyset_extra

    #define yyget_in yyget_in

    #define yyset_in yyset_in

    #define yyget_out yyget_out

    #define yyset_out yyset_out

    #define yyget_leng yyget_leng

    #define yyget_text yyget_text

    #define yyget_lineno yyget_lineno

    #define yyset_lineno yyset_lineno

    #define yywrap yywrap

    #define yyalloc yyalloc

    #define yyrealloc yyrealloc

    #define yyfree yyfree

    #define yytext yytext

    #define yyleng yyleng

    #define yyin yyin

    #define yyout yyout

    #define yy_flex_debug yy_flex_debug

    #define yylineno yylineno

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 60
#define YY_END_OF_BUFFER 61
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[352] =
    {   0,
       46,   46,    0,    0,    0,    0,   61,   59,   44,    1,
        1,   40,   47,   45,   39,   59,   21,   22,   37,   35,
       43,   36,   59,   38,   46,   46,   42,   29,   41,   30,
       45,   45,   25,   26,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       23,   59,   24,   48,   50,   50,   51,   49,   58,   57,
       55,   55,   58,    1,   32,    0,   52,    0,   45,   45,
       27,    3,    2,    0,   54,   53,    2,    0,    0,    0,
       46,    0,   33,   31,   34,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,    7,   45,

       45,   45,   45,   45,   45,   45,   45,   11,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   28,   50,   49,
       48,   55,    0,   56,    2,    0,    0,    0,   53,    2,
        0,    0,    2,    0,   46,   46,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,    3,   45,   45,
       45,   12,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,    0,    2,    2,    0,    2,    0,    0,

        2,    2,    0,   46,   46,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   10,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,    5,   19,   45,   45,    2,    0,    0,    2,    2,
        0,   45,   45,   45,   45,   45,   45,    6,   45,   45,
       45,   45,    3,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,    3,   45,   45,
       20,    0,   45,   18,    3,   45,   45,   45,   45,    9,
       45,   45,   45,   45,   45,   45,   45,   45,   15,   16,

       17,   45,   45,   45,   45,    8,    3,    0,   45,    4,
       45,   45,   45,   45,   45,   45,   45,   45,   45,    0,
        0,   45,   45,   45,   45,   45,   45,    0,    0,   45,
       45,   45,    0,    0,   45,    0,    0,   45,    0,    0,
        0,    0,    0,    0,    0,    0,   13,    0,    0,   14,
        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    1,    9,   10,   11,    1,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,    1,   22,   23,
       24,   25,    1,    1,    9,    9,    9,    9,   26,    9,
        9,    9,   27,    9,    9,    9,    9,    9,    9,    9,
        9,    9,   28,    9,    9,    9,    9,    9,    9,    9,
       29,   30,   31,    1,   32,    1,   33,   34,   35,   36,

       37,   38,   39,   40,   41,    9,   42,   43,   44,   45,
       46,   47,    9,   48,   49,   50,   51,   52,   53,   54,
       55,   56,   57,   58,   59,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[60] =
    {   0,
        1,    1,    2,    1,    2,    1,    1,    1,    3,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        3,    1,    1,    1,    1,    3,    3,    3,    1,    1,
        1,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    1,    1,    1
    } ;

static const flex_int16_t yy_base[359] =
    {   0,
        0,    0,   57,   58,   65,   69,  397, 1112, 1112, 1112,
      376,  349,   56,   55, 1112,  352, 1112, 1112, 1112,  344,
     1112,  331,   57,   66,   71,   75, 1112,  317,  313,  309,
       61,   78, 1112, 1112,   89,   84,   94,   98,  100,  126,
       96,  130,  132,  128,  137,  104,  142,  156,  135,  163,
     1112,  264, 1112, 1112, 1112,  315, 1112,  172, 1112, 1112,
     1112,  300,  112, 1112, 1112,  156, 1112,  181,  170,    0,
     1112, 1112,  186,  263, 1112,    0,  179,  207,  215,  217,
      222,  225, 1112, 1112, 1112,  230,  193,  232,  235,  240,
      188,  242,  244,  246,  249,  252,  254,  266,  256,  270,

      272,  277,  281,  285,  288,  290,  292,  294,  296,  300,
      308,  305,  311,  315,  319,  324,  326,  331,  336,  341,
      346,  351,  355,  357,  363,  365,  370, 1112, 1112, 1112,
     1112, 1112,  152, 1112,  383,  402,  348,  243,    0,  404,
      411,  367,  381,  417,  424,  437,  427,  419,  431,  445,
      447,  450,  374,  452,  455,  459,  457,  413,  462,  465,
      467,  470,  476,  479,  482,  488,  493,  497,  502,  504,
      507,  509,  512,  514,  516,  518,  520,  523,  532,  541,
      543,  545,  547,  549,  556,  558,  560,  562,  569,  564,
      576,  578,  582,  584,  595,  597,  244,  600,  610,  615,

      618,  620,  623,  627,  636,  640,  645,  649,  651,  654,
      656,  661,  664,  667,  671,  674,  676,  680,  685,  687,
      689,  691,  693,  698,  704,  708,  710,  716,  718,  724,
      726,  728,  733,  735,  739,  741,  744,  751,  753,  746,
      757,  762,  767,  769,  774,  776,  780,  228,  783,  793,
      796,  801,  803,  806,  810,  812,  814,  816,  819,  824,
      828,  832,  834,  836,  838,  840,  849,  852,  854,  858,
      861,  863,  870,  874,  879,  881,  883,  885,  891,  896,
      893,  231,  898,  902,  906,  915,  918,  920,  922,  924,
      927,  931,  933,  938,  935,  940,  944,  946,  954,  958,

      962,  964,  967,  969,  971, 1112,  977,  222,  973,  979,
      983,  987,  989,  995,  991,  997, 1001, 1004, 1013,  211,
      196, 1015, 1017, 1019, 1021, 1027, 1031,  191,  171, 1033,
     1038, 1040,  167,  183, 1046,  149,  147, 1049,  150,  125,
      133,   95,   84,   77,   63,   61, 1112,   59,   49, 1112,
     1112, 1096, 1099, 1102,   87, 1105,   81, 1108
    } ;

static const flex_int16_t yy_def[359] =
    {   0,
      351,    1,  352,  352,  353,  353,  351,  351,  351,  351,
      351,  351,  354,  355,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      355,  355,  351,  351,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      351,  351,  351,  351,  351,  351,  351,  356,  351,  351,
      351,  351,  351,  351,  351,  354,  351,  351,  355,  357,
      351,  351,  351,  351,  351,  358,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,

      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  358,  351,
      351,  351,  351,  351,  351,  351,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  351,  351,  351,  351,  351,  351,  351,

      351,  351,  351,  351,  351,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  351,  351,  351,  351,  351,
      351,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  351,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,

      355,  355,  355,  355,  355,  351,  355,  351,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  351,
      351,  355,  355,  355,  355,  355,  355,  351,  351,  355,
      355,  355,  351,  351,  355,  351,  351,  355,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
        0,  351,  351,  351,  351,  351,  351,  351
    } ;

static const flex_int16_t yy_nxt[1172] =
    {   0,
        8,    9,   10,    9,   11,    9,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   14,   31,   32,   33,    8,
       34,   14,   35,   36,   37,   38,   39,   40,   41,   14,
       42,   14,   43,   14,   44,   14,   45,   46,   47,   48,
       14,   49,   50,   14,   14,   14,   51,   52,   53,   55,
       55,   56,   56,   67,   57,   57,   60,   61,   60,   62,
       60,   61,   60,   62,   70,   70,   73,   73,   63,   75,
       70,   70,   63,   70,   76,   68,   58,   58,   77,   69,
       78,   78,   77,  350,   81,   81,   79,   70,   70,   74,

       79,  349,   80,   70,   70,   86,   82,   79,   70,   70,
      348,   79,  347,   70,   70,   70,   70,   70,   70,   70,
       70,  346,   89,   70,   70,  133,   94,   87,  345,   91,
      134,   92,   88,   95,   98,  344,   96,   90,   93,   97,
      118,  107,  100,   99,  101,   70,   70,   70,   70,   70,
       70,   70,   70,  102,   70,   70,   70,   70,  103,  343,
      112,   70,   70,   67,  113,  133,  104,  108,  105,  115,
      134,  106,  342,  109,  110,   70,   70,  111,  114,  131,
      126,  119,   70,   70,  116,   68,  341,  117,   66,   70,
       70,  120,  121,  340,  122,  124,  123,  339,  140,  140,

      337,  131,  127,  125,  141,  135,  135,   70,   70,  131,
       66,  136,   70,   70,  336,  141,  131,  137,   66,  131,
      334,  131,  136,  333,   77,   66,   78,   78,   66,  142,
       66,  142,   79,  152,  143,  143,  144,  144,   80,   77,
      148,   81,  145,   79,  146,  146,  329,   79,   80,   70,
       70,   70,   70,   82,   70,   70,   82,  328,   79,   70,
       70,   70,   70,   70,   70,   70,   70,  321,   70,   70,
      306,   70,   70,   70,   70,   70,   70,  282,  153,  147,
      149,  157,  248,  150,  158,   70,   70,  197,  151,   70,
       70,   70,   70,  154,  155,  156,   70,   70,  159,  138,

       70,   70,  132,  160,   70,   70,  161,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,  129,  162,   70,
       70,  128,  163,  165,   70,   70,  164,   70,   70,  166,
       70,   70,   85,  167,   70,   70,   84,  168,   70,   70,
       83,  169,  170,   70,   70,   70,   70,   72,  171,  172,
       70,   70,  173,  176,  174,   70,   70,  175,   72,  179,
       70,   70,   71,  168,  177,   70,   70,  196,  196,  178,
       70,   70,   65,  182,   70,   70,   70,   70,   64,  137,
      180,  181,   70,   70,   70,   70,  143,  143,  183,   70,
       70,  185,  184,   70,   70,  189,  351,  187,  351,  186,

      202,  202,  135,  135,  188,  191,  212,  192,  136,  351,
      193,  351,  203,  190,  137,  351,  194,  168,  194,  136,
      351,  195,  195,  198,  198,  200,  351,  200,  351,  141,
      201,  201,   70,   70,   77,  199,   78,   78,   70,   70,
      141,   77,   79,   81,  145,  351,   70,   70,   80,   79,
       70,   70,  351,   79,   77,   82,  204,  205,  351,  207,
       79,  214,   79,  206,   70,   70,   70,   70,   82,   70,
       70,   70,   70,   79,   70,   70,   70,   70,   70,   70,
      208,   70,   70,  210,   70,   70,   70,   70,  168,   70,
       70,  168,  211,  213,  209,   70,   70,  217,   70,   70,

      218,   70,   70,  351,  168,  351,  219,   70,   70,  351,
      215,  216,   70,   70,  351,  220,   70,   70,  351,  168,
      222,   70,   70,   70,   70,  223,   70,   70,   70,   70,
      221,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,  351,   70,   70,  351,  227,  224,  168,  351,  225,
      168,   70,   70,  351,  228,  351,  226,  351,  168,  229,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
      351,  230,  231,  351,  232,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,  237,  351,  236,   70,   70,
      234,  233,  239,  351,  235,   70,   70,   70,   70,  351,

      242,   70,   70,  195,  195,  238,  351,  240,  168,  351,
      244,  243,  351,  241,  246,  246,  135,  135,  351,  198,
      198,  351,  136,  351,  245,  141,  247,  351,  137,  249,
      249,  199,  351,  136,  201,  201,  141,  250,  250,  202,
      202,  199,  202,  202,   77,  351,  204,  205,  351,  251,
      351,  203,   79,   77,  203,  204,  205,  351,   82,   70,
       70,   79,  351,   79,   70,   70,  351,   82,   70,   70,
       70,   70,   79,   70,   70,   70,   70,  351,  252,  351,
       70,   70,  351,   70,   70,  254,   70,   70,  351,  253,
       70,   70,  257,   70,   70,   70,   70,  351,  255,   70,

       70,  256,  168,  168,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,  259,  258,  351,   70,   70,  351,
      168,  351,  261,   70,   70,  242,  260,   70,   70,   70,
       70,  262,  351,  263,  264,   70,   70,   70,   70,  351,
      266,  351,  168,   70,   70,   70,   70,   70,   70,  351,
      269,  265,   70,   70,   70,   70,  270,  267,   70,   70,
       70,   70,  271,   70,   70,   70,   70,  268,  272,  351,
       70,   70,   70,   70,  351,  275,   70,   70,  351,  274,
      273,   70,   70,  351,  168,  276,   70,   70,   70,   70,
      351,  168,  277,   70,   70,  246,  246,  351,  278,  246,

      246,  351,  198,  198,  351,  279,  351,  247,  141,  351,
      281,  247,  250,  250,  199,  250,  250,  351,  280,  141,
       70,   70,   70,   70,  251,   70,   70,  251,  351,   70,
       70,   70,   70,   70,   70,   70,   70,  283,   70,   70,
      351,  284,  286,   70,   70,  351,  287,   70,   70,  285,
      351,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,  168,  351,  288,  290,  351,  289,  291,   70,   70,
      351,   70,   70,   70,   70,  351,  292,   70,   70,  293,
       70,   70,   70,   70,  294,  351,  295,  168,  168,   70,
       70,  351,  296,   70,   70,  298,  351,  299,   70,   70,

       70,   70,   70,   70,   70,   70,  351,  297,  301,  351,
       70,   70,   70,   70,  300,   70,   70,   70,   70,  351,
      168,   70,   70,  308,  351,   70,   70,  351,  302,  351,
      303,  304,  351,  168,   70,   70,  305,   70,   70,   70,
       70,   70,   70,   70,   70,  307,   70,   70,  351,  309,
       70,   70,   70,   70,   70,   70,  351,   70,   70,   70,
       70,  351,  310,   70,   70,   70,   70,  314,  351,  312,
      311,  168,  313,   70,   70,  168,  168,   70,   70,  351,
      168,   70,   70,   70,   70,  168,   70,   70,   70,   70,
       70,   70,   70,   70,  320,  315,   70,   70,   70,   70,

      351,  316,   70,   70,  351,  318,   70,   70,   70,   70,
       70,   70,  317,  319,   70,   70,   70,   70,  351,  168,
       70,   70,  168,   70,   70,  323,  351,  325,  351,  324,
      351,  322,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,  351,  168,  351,  326,   70,   70,  327,  168,
       70,   70,   70,   70,  351,  168,  168,   70,   70,   70,
       70,  351,  331,  351,  330,   70,   70,  332,   70,   70,
      351,  351,  351,  351,  351,  168,  351,  351,  351,  351,
      168,  168,  338,  351,  168,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  335,   54,   54,   54,   59,

       59,   59,   66,  351,   66,  130,  351,  130,  139,  351,
      139,    7,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351
    } ;

static const flex_int16_t yy_chk[1172] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        4,    3,    4,   13,    3,    4,    5,    5,    5,    5,
        6,    6,    6,    6,   14,   14,   23,   23,    5,   24,
       31,   31,    6,  357,   24,   13,    3,    4,   25,  355,
       25,   25,   26,  349,   26,   26,   25,   32,   32,   23,

       26,  348,   25,   36,   36,   31,   26,   25,   35,   35,
      346,   26,  345,   37,   37,   41,   41,   38,   38,   39,
       39,  344,   35,   46,   46,   63,   37,   32,  343,   36,
       63,   36,   32,   37,   38,  342,   37,   35,   36,   37,
       46,   41,   39,   38,   39,   40,   40,   44,   44,   42,
       42,   43,   43,   39,   49,   49,   45,   45,   40,  341,
       44,   47,   47,   66,   44,  133,   40,   42,   40,   45,
      133,   40,  340,   42,   42,   48,   48,   43,   44,   58,
       49,   47,   50,   50,   45,   66,  339,   45,   68,   69,
       69,   47,   47,  337,   47,   48,   47,  336,   77,   77,

      334,   58,   50,   48,   77,   73,   73,   91,   91,   58,
       68,   73,   87,   87,  333,   77,   58,   73,   68,   58,
      329,   58,   73,  328,   78,   68,   78,   78,   68,   79,
       68,   79,   78,   91,   79,   79,   80,   80,   78,   81,
       87,   81,   81,   78,   82,   82,  321,   81,   80,   86,
       86,   88,   88,   81,   89,   89,   82,  320,   81,   90,
       90,   92,   92,   93,   93,   94,   94,  308,   95,   95,
      282,   96,   96,   97,   97,   99,   99,  248,   92,   86,
       88,   95,  197,   89,   96,   98,   98,  138,   90,  100,
      100,  101,  101,   93,   94,   94,  102,  102,   97,   74,

      103,  103,   62,   98,  104,  104,   99,  105,  105,  106,
      106,  107,  107,  108,  108,  109,  109,   56,  100,  110,
      110,   52,  101,  103,  112,  112,  102,  111,  111,  104,
      113,  113,   30,  105,  114,  114,   29,  106,  115,  115,
       28,  107,  109,  116,  116,  117,  117,   22,  110,  110,
      118,  118,  111,  115,  112,  119,  119,  114,   20,  117,
      120,  120,   16,  113,  116,  121,  121,  137,  137,  116,
      122,  122,   12,  120,  123,  123,  124,  124,   11,  137,
      118,  119,  125,  125,  126,  126,  142,  142,  120,  127,
      127,  122,  121,  153,  153,  125,    7,  124,    0,  123,

      143,  143,  135,  135,  124,  126,  153,  126,  135,    0,
      127,    0,  143,  125,  135,    0,  136,  125,  136,  135,
        0,  136,  136,  140,  140,  141,    0,  141,    0,  140,
      141,  141,  158,  158,  144,  140,  144,  144,  148,  148,
      140,  145,  144,  145,  145,    0,  147,  147,  144,  145,
      149,  149,    0,  144,  146,  145,  146,  146,    0,  148,
      145,  158,  146,  147,  150,  150,  151,  151,  146,  152,
      152,  154,  154,  146,  155,  155,  157,  157,  156,  156,
      149,  159,  159,  151,  160,  160,  161,  161,  154,  162,
      162,  155,  152,  156,  150,  163,  163,  160,  164,  164,

      161,  165,  165,    0,  157,    0,  162,  166,  166,    0,
      159,  159,  167,  167,    0,  164,  168,  168,    0,  163,
      166,  169,  169,  170,  170,  167,  171,  171,  172,  172,
      165,  173,  173,  174,  174,  175,  175,  176,  176,  177,
      177,    0,  178,  178,    0,  172,  170,  169,    0,  170,
      173,  179,  179,    0,  174,    0,  171,    0,  175,  176,
      180,  180,  181,  181,  182,  182,  183,  183,  184,  184,
        0,  177,  178,    0,  179,  185,  185,  186,  186,  187,
      187,  188,  188,  190,  190,  184,    0,  183,  189,  189,
      181,  180,  186,    0,  182,  191,  191,  192,  192,    0,

      190,  193,  193,  194,  194,  185,    0,  188,  187,    0,
      192,  191,    0,  189,  195,  195,  196,  196,    0,  198,
      198,    0,  196,    0,  193,  198,  195,    0,  196,  199,
      199,  198,    0,  196,  200,  200,  198,  201,  201,  202,
      202,  199,  203,  203,  204,    0,  204,  204,    0,  201,
        0,  202,  204,  205,  203,  205,  205,    0,  204,  206,
      206,  205,    0,  204,  207,  207,    0,  205,  208,  208,
      209,  209,  205,  210,  210,  211,  211,    0,  206,    0,
      212,  212,    0,  213,  213,  208,  214,  214,    0,  207,
      215,  215,  211,  216,  216,  217,  217,    0,  209,  218,

      218,  210,  212,  213,  219,  219,  220,  220,  221,  221,
      222,  222,  223,  223,  216,  214,    0,  224,  224,    0,
      215,    0,  218,  225,  225,  221,  217,  226,  226,  227,
      227,  220,    0,  222,  224,  228,  228,  229,  229,    0,
      226,    0,  223,  230,  230,  231,  231,  232,  232,    0,
      229,  225,  233,  233,  234,  234,  230,  227,  235,  235,
      236,  236,  231,  237,  237,  240,  240,  228,  232,    0,
      238,  238,  239,  239,    0,  236,  241,  241,    0,  235,
      233,  242,  242,    0,  234,  238,  243,  243,  244,  244,
        0,  237,  239,  245,  245,  246,  246,    0,  240,  247,

      247,    0,  249,  249,    0,  241,    0,  246,  249,    0,
      245,  247,  250,  250,  249,  251,  251,    0,  244,  249,
      252,  252,  253,  253,  250,  254,  254,  251,    0,  255,
      255,  256,  256,  257,  257,  258,  258,  252,  259,  259,
        0,  253,  255,  260,  260,    0,  257,  261,  261,  254,
        0,  262,  262,  263,  263,  264,  264,  265,  265,  266,
      266,  256,    0,  259,  261,    0,  260,  262,  267,  267,
        0,  268,  268,  269,  269,    0,  263,  270,  270,  264,
      271,  271,  272,  272,  266,    0,  267,  265,  268,  273,
      273,    0,  269,  274,  274,  271,    0,  272,  275,  275,

      276,  276,  277,  277,  278,  278,    0,  270,  274,    0,
      279,  279,  281,  281,  273,  280,  280,  283,  283,    0,
      276,  284,  284,  285,    0,  285,  285,    0,  275,    0,
      277,  279,    0,  278,  286,  286,  280,  287,  287,  288,
      288,  289,  289,  290,  290,  283,  291,  291,    0,  286,
      292,  292,  293,  293,  295,  295,    0,  294,  294,  296,
      296,    0,  287,  297,  297,  298,  298,  295,    0,  293,
      288,  289,  294,  299,  299,  291,  296,  300,  300,    0,
      297,  301,  301,  302,  302,  292,  303,  303,  304,  304,
      305,  305,  309,  309,  307,  298,  307,  307,  310,  310,

        0,  302,  311,  311,    0,  304,  312,  312,  313,  313,
      315,  315,  303,  305,  314,  314,  316,  316,    0,  311,
      317,  317,  309,  318,  318,  313,    0,  315,    0,  314,
        0,  312,  319,  319,  322,  322,  323,  323,  324,  324,
      325,  325,    0,  316,    0,  317,  326,  326,  318,  319,
      327,  327,  330,  330,    0,  324,  325,  331,  331,  332,
      332,    0,  323,    0,  322,  335,  335,  326,  338,  338,
        0,    0,    0,    0,    0,  331,    0,    0,    0,    0,
      327,  330,  335,    0,  338,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  332,  352,  352,  352,  353,

      353,  353,  354,    0,  354,  356,    0,  356,  358,    0,
      358,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "jac.l"
#line 2 "jac.l"
	#include <stdio.h>
	#include <string.h>
	
	#include "y.tab.h"
	#include "ast.h"

	node_t* ast_root;

	int print_flag = 0;
	int syntax_flag = 0;

	int line = 1;
	int col = 1;

	int comment_begin = 0;
	int str_begin = 0;
	
	int line_begin = 0;
#line 906 "lex.yy.c"

#line 908 "lex.yy.c"

#define INITIAL 0
#define str_state 1
#define comment 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 39 "jac.l"


#line 1130 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 352 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1112 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 41 "jac.l"
{col=1; line++;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 42 "jac.l"
{col+=yyleng; if(print_flag) printf("REALLIT(%s)\n", yytext); if(syntax_flag) {yylval.str = (char*) strdup(yytext); return REALLIT;}}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 45 "jac.l"
{col+=yyleng; if(print_flag) printf("RESERVED(%s)\n", yytext); if(syntax_flag) {yylval.str = (char*) strdup(yytext); return RESERVED;}}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 46 "jac.l"
{col+=yyleng; if(print_flag) printf("BOOL\n"); if(syntax_flag) {yylval.str = (char*) strdup(yytext); return BOOL;}}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 47 "jac.l"
{col+=yyleng; if(print_flag) printf("BOOLLIT(%s)\n", yytext); if(syntax_flag) {yylval.str = (char*) strdup(yytext); return BOOLLIT;}}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 48 "jac.l"
{col+=yyleng; if(print_flag) printf("CLASS\n"); if(syntax_flag) {yylval.str = (char*) strdup(yytext); return CLASS;}}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 49 "jac.l"
{col+=yyleng; if(print_flag) printf("DO\n"); if(syntax_flag) {yylval.str = (char*) strdup(yytext); return DO;}}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 50 "jac.l"
{col+=yyleng; if(print_flag) printf("DOTLENGTH\n"); if(syntax_flag) {yylval.str = (char*) strdup(yytext); return DOTLENGTH;}}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 51 "jac.l"
{col+=yyleng; if(print_flag) printf("DOUBLE\n"); if(syntax_flag) {yylval.str = (char*) strdup(yytext); return DOUBLE;}}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 52 "jac.l"
{col+=yyleng; if(print_flag) printf("ELSE\n"); if(syntax_flag) {yylval.str = (char*) strdup(yytext); return ELSE;}}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 53 "jac.l"
{col+=yyleng; if(print_flag) printf("IF\n"); if(syntax_flag) {yylval.str = (char*) strdup(yytext); return IF;}}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 54 "jac.l"
{col+=yyleng; if(print_flag) printf("INT\n"); if(syntax_flag) {yylval.str = (char*) strdup(yytext); return INT;}}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 55 "jac.l"
{col+=yyleng; if(print_flag) printf("PARSEINT\n"); if(syntax_flag) {yylval.str = (char*) strdup(yytext); return PARSEINT;}}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 56 "jac.l"
{col+=yyleng; if(print_flag) printf("PRINT\n"); if(syntax_flag) {yylval.str = (char*) strdup(yytext); return PRINT;}}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 57 "jac.l"
{col+=yyleng; if(print_flag) printf("PUBLIC\n"); if(syntax_flag) {yylval.str = (char*) strdup(yytext); return PUBLIC;}}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 58 "jac.l"
{col+=yyleng; if(print_flag) printf("RETURN\n"); if(syntax_flag) {yylval.str = (char*) strdup(yytext); return RETURN;}}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 59 "jac.l"
{col+=yyleng; if(print_flag) printf("STATIC\n"); if(syntax_flag) {yylval.str = (char*) strdup(yytext); return STATIC;}}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 60 "jac.l"
{col+=yyleng; if(print_flag) printf("STRING\n"); if(syntax_flag) {yylval.str = (char*) strdup(yytext); return STRING;}}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 61 "jac.l"
{col+=yyleng; if(print_flag) printf("VOID\n"); if(syntax_flag) {yylval.str = (char*) strdup(yytext); return VOID;}}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 62 "jac.l"
{col+=yyleng; if(print_flag) printf("WHILE\n"); if(syntax_flag) {yylval.str = (char*) strdup(yytext); return WHILE;}}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 63 "jac.l"
{col+=yyleng; if(print_flag) printf("OCURV\n"); if(syntax_flag) {yylval.str = (char*) strdup(yytext); return OCURV;}}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 64 "jac.l"
{col+=yyleng; if(print_flag) printf("CCURV\n"); if(syntax_flag) {yylval.str = (char*) strdup(yytext); return CCURV;}}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 65 "jac.l"
{col+=yyleng; if(print_flag) printf("OBRACE\n"); if(syntax_flag) {yylval.str = (char*) strdup(yytext); return OBRACE;}}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 66 "jac.l"
{col+=yyleng; if(print_flag) printf("CBRACE\n"); if(syntax_flag) {yylval.str = (char*) strdup(yytext); return CBRACE;}}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 67 "jac.l"
{col+=yyleng; if(print_flag) printf("OSQUARE\n"); if(syntax_flag) {yylval.str = (char*) strdup(yytext); return OSQUARE;}}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 68 "jac.l"
{col+=yyleng; if(print_flag) printf("CSQUARE\n"); if(syntax_flag) {yylval.str = (char*) strdup(yytext); return CSQUARE;}}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 69 "jac.l"
{col+=yyleng; if(print_flag) printf("AND\n"); if(syntax_flag) {yylval.str = (char*) strdup(yytext); return AND;}}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 70 "jac.l"
{col+=yyleng; if(print_flag) printf("OR\n"); if(syntax_flag) {yylval.str = (char*) strdup(yytext); return OR;}}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 71 "jac.l"
{col+=yyleng; if(print_flag) printf("LT\n"); if(syntax_flag) {yylval.str = (char*) strdup(yytext); return LT;}}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 72 "jac.l"
{col+=yyleng; if(print_flag) printf("GT\n"); if(syntax_flag) {yylval.str = (char*) strdup(yytext); return GT;}}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 73 "jac.l"
{col+=yyleng; if(print_flag) printf("EQ\n"); if(syntax_flag) {yylval.str = (char*) strdup(yytext); return EQ;}}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 74 "jac.l"
{col+=yyleng; if(print_flag) printf("NEQ\n"); if(syntax_flag) {yylval.str = (char*) strdup(yytext); return NEQ;}}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 75 "jac.l"
{col+=yyleng; if(print_flag) printf("LEQ\n"); if(syntax_flag) {yylval.str = (char*) strdup(yytext); return LEQ;}}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 76 "jac.l"
{col+=yyleng; if(print_flag) printf("GEQ\n"); if(syntax_flag) {yylval.str = (char*) strdup(yytext); return GEQ;}}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 77 "jac.l"
{col+=yyleng; if(print_flag) printf("PLUS\n"); if(syntax_flag) {yylval.str = (char*) strdup(yytext); return PLUS;}}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 78 "jac.l"
{col+=yyleng; if(print_flag) printf("MINUS\n"); if(syntax_flag) {yylval.str = (char*) strdup(yytext); return MINUS;}}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 79 "jac.l"
{col+=yyleng; if(print_flag) printf("STAR\n"); if(syntax_flag) {yylval.str = (char*) strdup(yytext); return STAR;}}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 80 "jac.l"
{col+=yyleng; if(print_flag) printf("DIV\n"); if(syntax_flag) {yylval.str = (char*) strdup(yytext); return DIV;}}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 81 "jac.l"
{col+=yyleng; if(print_flag) printf("MOD\n"); if(syntax_flag) {yylval.str = (char*) strdup(yytext); return MOD;}}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 82 "jac.l"
{col+=yyleng; if(print_flag) printf("NOT\n"); if(syntax_flag) {yylval.str = (char*) strdup(yytext); return NOT;}}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 83 "jac.l"
{col+=yyleng; if(print_flag) printf("ASSIGN\n"); if(syntax_flag) {yylval.str = (char*) strdup(yytext); return ASSIGN;}}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 84 "jac.l"
{col+=yyleng; if(print_flag) printf("SEMI\n"); if(syntax_flag) {yylval.str = (char*) strdup(yytext); return SEMI;}}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 85 "jac.l"
{col+=yyleng; if(print_flag) printf("COMMA\n"); if(syntax_flag) {yylval.str = (char*) strdup(yytext); return COMMA;}}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 87 "jac.l"
{col+=yyleng;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 88 "jac.l"
{col+=yyleng; if(print_flag) printf("ID(%s)\n", yytext); if(syntax_flag) {yylval.str = (char*) strdup(yytext); return ID;}}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 89 "jac.l"
{col+=yyleng; if(print_flag) printf("DECLIT(%s)\n", yytext); if(syntax_flag) {yylval.str = (char*) strdup(yytext); return DECLIT;}}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 91 "jac.l"
{str_begin=col; col+=yyleng; BEGIN(str_state);}
	YY_BREAK

case 48:
YY_RULE_SETUP
#line 93 "jac.l"
col+=yyleng;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 94 "jac.l"
printf("Line %d, col %d: invalid escape sequence (%s)\n", line, col, yytext); col+=yyleng;  
	YY_BREAK
case 50:
/* rule 50 can match eol */
YY_RULE_SETUP
#line 95 "jac.l"
col=1; printf("Line %d, col %d: unterminated string literal\n", line, str_begin); line++; BEGIN(0);  
	YY_BREAK
case YY_STATE_EOF(str_state):
#line 96 "jac.l"
printf("Line %d, col %d: unterminated string literal\n", line, str_begin); col += 1; return 0; yyterminate();
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 97 "jac.l"
col+=yyleng; BEGIN(0);
	YY_BREAK

case 52:
YY_RULE_SETUP
#line 100 "jac.l"
{col+=yyleng; if(print_flag) printf("STRLIT(%s)\n", yytext); if(syntax_flag) {yylval.str = (char*) strdup(yytext); return STRLIT;}}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 102 "jac.l"
{col+=yyleng;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 104 "jac.l"
{comment_begin=col; line_begin=line; col+=yyleng; BEGIN(comment);}
	YY_BREAK
case 55:
/* rule 55 can match eol */
YY_RULE_SETUP
#line 105 "jac.l"
{col=1; line++;}
	YY_BREAK
case YY_STATE_EOF(comment):
#line 106 "jac.l"
{printf("Line %d, col %d: unterminated comment\n", line_begin, comment_begin); col+=1; return 0; yyterminate();}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 107 "jac.l"
{col += yyleng; BEGIN(0);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 108 "jac.l"
{col++;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 109 "jac.l"
{col += yyleng;}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 112 "jac.l"
{col+=1; return 0;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 113 "jac.l"
{printf("Line %d, col %d: illegal character (%c)\n", line, col, yytext[0]); col+=yyleng;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 115 "jac.l"
ECHO;
	YY_BREAK
#line 1504 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,(yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,(yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 352 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 352 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 351);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc((yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes(yystr,(int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 115 "jac.l"


int main(int argc, char** argv) 
{
	if(argc == 2) {
		if(!strcmp(argv[1],"-l")) {
			print_flag = 1;
			yylex();
		} else if(!strcmp(argv[1], "-t") || !strcmp(argv[1], "-2")) {
			print_flag = 0;
			syntax_flag = 1;
			yyparse();
			if(!error_flag)
				print_ast_tree(ast_root, 0);
		}
	} else if(argc == 1) {
		syntax_flag = 1;
		yyparse();
	}
	return 0;
}

int yywrap() 
{
	return 1;
}
